In [35]:
import numpy as np
from numpy.linalg import norm
A = np.array([[1,1,4,0,100,10],
              [0,5,9,0,300,8],
              [1,7,4,0,10,1]])

A_per = np.array([[0,2,1,8,5,2],
                  [0,0,3,18,4,10],
                  [0,2,0.1,8,0.5,14]])

In [8]:
from munkres import Munkres
import numpy as np
from numpy.linalg import norm
'''
Compute:
       errW = min_perm ||W - West(:,perm)||_F / ||W||_F
'''
def compareWs(W,West):
    r = W.shape[1]
    DIST = np.zeros((r,r))
    for i in range(r):
        for j in range(r):
            DIST[i,j] = norm(W[:,i] - West[:,j])**2
    m = Munkres()
    indexes = m.compute(DIST)
    print(indexes)
    # errW = norm( W - West[:,indexes] , 'fro' ) / norm(W,'fro')
    for (k, l) in indexes:
       print(W[:,k], West[:,l])
    

In [36]:
from munkres import Munkres
import numpy as np
from numpy.linalg import norm
'''
Compute:
       errW = min_perm ||W - West(:,perm)||_F / ||W||_F
'''
def col_normalization(W):
    norms = np.linalg.norm(W, axis=0)
    norms[norms==0] = 1
    W_normalized = W / norms[None,:]
    return W_normalized

'''
This is actually computing NAE
'''
def compareWs_fast(W,West):
    r = W.shape[1]
    W_temp = col_normalization(W)
    West_temp = col_normalization(West)
    W_expanded = W_temp[:,:,None]
    West_expanded = West_temp[:,None,:]
    DIST = np.sum((W_expanded - West_expanded)**2, axis=0)
    m = Munkres()
    indexes = m.compute(DIST)
    print(indexes)
    row_indexes, col_indexes = zip(*indexes)
    W_reordered = W[:,row_indexes]
    West_reordered = West[:,col_indexes]
    return W_reordered, West_reordered

In [37]:
W_new, West_new = compareWs_fast(A,A_per)
# rel = compareWs(A,A_per)

print(W_new)
print("\n")
print(West_new)

[(0, 1), (1, 5), (2, 3), (3, 0), (4, 2), (5, 4)]
[[  1   1   4   0 100  10]
 [  0   5   9   0 300   8]
 [  1   7   4   0  10   1]]


[[ 2.   2.   8.   0.   1.   5. ]
 [ 0.  10.  18.   0.   3.   4. ]
 [ 2.  14.   8.   0.   0.1  0.5]]
