In [1]:
import numpy as np
from numpy.linalg import norm
A = np.array([[1,1,4,100,10,0],
              [0,5,9,300,8,0],
              [1,7,4,10,1,0]])

A_per = np.array([[0,2,1,8,5,2],
                  [0,0,3,18,4,10],
                  [0,2,0.1,8,0.5,14]])

In [2]:
from munkres import Munkres
import numpy as np
from numpy.linalg import norm
'''
Compute:
       errW = min_perm ||W - West(:,perm)||_F / ||W||_F
'''
def col_normalization_l2(W):
    norms = np.linalg.norm(W, axis=0)
    norms[norms==0] = 1
    W_normalized = W / norms[None,:]
    return W_normalized

'''
This is actually computing MSE between W and West (2-norm)
'''
def compareWs_fast_l2(W,West):
    r = W.shape[1]
    W_temp = col_normalization_l2(W)
    West_temp = col_normalization_l2(West)
    W_expanded = W_temp[:,:,None]
    West_expanded = West_temp[:,None,:]
    DIST = np.sum((W_expanded - West_expanded)**2, axis=0)
    m = Munkres()
    indexes = m.compute(DIST)
    print(indexes)
    row_indexes, col_indexes = zip(*indexes)
    W_reordered = W[:,row_indexes]
    West_reordered = West[:,col_indexes]
    return W_reordered, West_reordered

In [3]:
W_new, West_new = compareWs_fast_l2(A,A_per)
# rel = compareWs(A,A_per)

print(W_new)
print("\n")
print(West_new)

[(0, 1), (1, 5), (2, 3), (3, 2), (4, 4), (5, 0)]
[[  1   1   4 100  10   0]
 [  0   5   9 300   8   0]
 [  1   7   4  10   1   0]]


[[ 2.   2.   8.   1.   5.   0. ]
 [ 0.  10.  18.   3.   4.   0. ]
 [ 2.  14.   8.   0.1  0.5  0. ]]


In [43]:
from munkres import Munkres
import numpy as np
from numpy.linalg import norm


def col_normalization_l1(W):
    norms = np.linalg.norm(W, axis=0,ord = 1)
    norms[norms==0] = 1
    W_normalized = W / norms[None,:]
    return W_normalized

'''
This is actually computing NAE between W and West (1-norm)
'''
def compareWs_fast_l1(W,West):
    r = W.shape[1]
    W_temp = col_normalization_l1(W)
    West_temp = col_normalization_l1(West)
    W_expanded = W_temp[:,:,None]
    West_expanded = West_temp[:,None,:]
    DIST = np.sum(np.abs(W_expanded - West_expanded), axis=0)
    m = Munkres()
    indexes = m.compute(DIST)
    print(indexes)
    row_indexes, col_indexes = zip(*indexes)
    W_reordered = W[:,row_indexes]
    West_reordered = West[:,col_indexes]
    return W_reordered, West_reordered

In [44]:
W_new, West_new = compareWs_fast_l1(A,A_per)
# rel = compareWs(A,A_per)

print(W_new)
print("\n")
print(West_new)

[(0, 1), (1, 5), (2, 3), (3, 2), (4, 4), (5, 0)]
[[  1   1   4 100  10   0]
 [  0   5   9 300   8   0]
 [  1   7   4  10   1   0]]


[[ 2.   2.   8.   1.   5.   0. ]
 [ 0.  10.  18.   3.   4.   0. ]
 [ 2.  14.   8.   0.1  0.5  0. ]]
